backpacks:
  small:
    size: 1024
    maxItems: 3
    menu:
      type: "CHEST"
      title: "§8Small Backpack"
      item:
        material: "RED_STAINED_GLASS_PANE"
        lore:
          - ""
          - "§7<amount>/<amountMax>"
          - ""
      partition: "000000000 000111000 000000000" # 0's are the item defined above 1's are free item slots
    name: "Small Backpack"
    glow: false
    item: CHEST
    lore:
      - ""
      - "Some small lore here"
      - "Another small lore here"
      - ""
  medium:
    size: 10048
    maxItems: 5
    menu:
      type: "CHEST"
      title: "§8Medium Backpack" # Title displayed in menu
      item:
        material: "RED_STAINED_GLASS_PANE"
        lore:
          - ""
          - "§7<amount>/<amountMax>"
          - ""
      partition: "000000000 001111100 000000000" # 0's are the item defined above 1's are free item slots
    name: "§7Medium Backpack" # Name of item
    glow: false
    item: TRAPPED_CHEST
    lore:
      - ""
      - "Medium lore here"
      - "Another medium lore here"
      - ""
  large:
    size: 100032
    maxItems: 9
    menu:
      type: "CHEST"
      title: "§8Large Backpack" # Title displayed in menu
      item:
        material: "RED_STAINED_GLASS_PANE"
        lore:
          - ""
          - "§7<amount>/<amountMax>"
          - ""
      partition: "000000000 111111111 000000000" # 0's are the item defined above 1's are free item slots
    name: "Large Backpack"
    glow: true
    item: ENDER_CHEST
    lore:
      - ""
      - "Large lore here"
      - "Another large lore here"
      - ""


harvesterhoe:
  blocks:
    # Something here? List of Blocks
  upgrades:
    wheat:
      1: 10
      2: 20
      3: 30
      4: 40
    carrots:
      1: 10
      2: 20
      3: 30
      4: 40
    potatoes:
      1: 10
      2: 20
      3: 30
      4: 40
    beetroot:
      1: 10
      2: 20
      3: 30
      4: 40
    bamboo:
      1: 10
      2: 20
      3: 30
      4: 40
    sugar_cane:
      1: 10
      2: 20
      3: 30
      4: 40
    kelp:
      1: 10
      2: 20
      3: 30
      4: 40

