backpacks:
  small:
    size: 1024
    maxItems: 3
    name: "Small Backpack"
    glow: false
    item: CHEST
    lore:
      - ""
      - "Some small lore here"
      - "Another small lore here"
      - ""
  medium:
    size: 10048
    maxItems: 6
    name: "Medium Backpack"
    glow: false
    item: TRAPPED_CHEST
    lore:
      - ""
      - "Medium lore here"
      - "Another medium lore here"
      - ""
  large:
    size: 100032
    maxItems: 9
    name: "Large Backpack"
    glow: true
    item: ENDER_CHEST
    lore:
      - ""
      - "Large lore here"
      - "Another large lore here"
      - ""


harvesterhoe:
  blocks:
    # Something here? List of Blocks
  upgrades:
    wheat:
      1: 10
      2: 20
      3: 30
      4: 40
    carrots:
      1: 10
      2: 20
      3: 30
      4: 40
    potatoes:
      1: 10
      2: 20
      3: 30
      4: 40
    beetroot:
      1: 10
      2: 20
      3: 30
      4: 40
    bamboo:
      1: 10
      2: 20
      3: 30
      4: 40
    sugar_cane:
      1: 10
      2: 20
      3: 30
      4: 40
    kelp:
      1: 10
      2: 20
      3: 30
      4: 40

