backpacks:
  small:
    size: 1024
    maxItems: 3
    menu:
      type: "CHEST"
      title: "§8Small Backpack"
      item:
        material: "RED_STAINED_GLASS_PANE"
        lore:
          - ""
          - "§7<amount>/<amountMax>"
          - ""
      partition: "000000000 000111000 000000000" # 0's are the item defined above 1's are free item slots
    name: "Small Backpack"
    glow: false
    item: CHEST
    lore:
      - ""
      - "Some small lore here"
      - "Another small lore here"
      - ""
  medium:
    size: 10048
    maxItems: 5
    menu:
      type: "CHEST"
      title: "§8Medium Backpack" # Title displayed in menu
      item:
        material: "RED_STAINED_GLASS_PANE"
        lore:
          - ""
          - "§7<amount>/<amountMax>"
          - ""
      partition: "000000000 001111100 000000000" # 0's are the item defined above 1's are free item slots
    name: "§7Medium Backpack" # Name of item
    glow: false
    item: TRAPPED_CHEST
    lore:
      - ""
      - "Medium lore here"
      - "Another medium lore here"
      - ""
  large:
    size: 100032
    maxItems: 9
    menu:
      type: "CHEST"
      title: "§8Large Backpack" # Title displayed in menu
      item:
        material: "RED_STAINED_GLASS_PANE" # Item displayed in "0" slots
        lore: # Lore for items in "1" slots
          - ""
          - "§7<amount>/<amountMax>"
          - ""
      partition: "000000000 111111111 000000000" # 0's are the item defined above 1's are free item slots
    name: "Large Backpack"
    glow: true
    item: ENDER_CHEST
    lore:
      - ""
      - "Large lore here"
      - "Another large lore here"
      - ""


harvesterhoe:
  # Example template
  # Blocks = list of blocks this item effects
  item:
    material: "NETHERITE_HOE" #Hoe item
    name: "Harvester Hoe" # Name of item
    lore: # Lore displayed on harvesterhoe
      - ""
      - "Lore here"
      - "lore here 2"
      - ""
    glow: true # Whether the hoe will glow
    unbreakable: true # Whether the hoe will break
  blocks: # Example
    - wheat
    - beetroot
    - carrots
    - potato
    - bamboo
  menu:
    #type: "CHEST"
    title: "Upgrade Menu"
    items:
      pane: "GRAY_STAINED_GLASS_PANE"
      upgrade:
        lore:
          - ""
          - "Current Level: <level>"
          - ""
          - "Click to upgrade the <type> multiplier!"
          - "Cost: <cost>"
          - ""
          - "Right click to upgrade"
    partition: "000000000 000111000 000111000 000000000" # In Slots of 9 for each row of a inventory anything greater than 27 doesn't require a 'type'
  upgrades:
    wheat:
      levels:
        1: 30
        2: 40
        3: 50
        4: 60
    carrots:
      levels:
        1: 20
        2: 30
        3: 40
        4: 50
    beetroot:
      levels:
        1: 20
        2: 30
        3: 40
        4: 50
    potato:
      levels:
        1: 20
        2: 30
        3: 40
        4: 50
    bamboo:
      levels:
        1: 20
        2: 30
        3: 40
        4: 50