name: Premiumharvesterhoe
version: '${project.version}'
main: me.c0dev.Main
api-version: 1.18
commands:
  givePremiumHarvesterHoe:
    description: Gives the player a harvester hoe
    usage: /givePremiumHarvesterHoe
  getUUID:
    description: Gives the player the UUID of a custom item
    usage: /getUUID
  giveBP:
    description: Gives a backpack
    usage: /giveBP <type>
  dumpBPData:
    description: Dumps Backpack information
    usage: /dumpBPData
